### ISSUE TITLE
recognation model 

### ISSUE THREAD

**Issue by Globolik** [duclong1009/OCR-deepLearning#4]
Hi Duc Long!
Great job on OCR-dl project. I'm curious about recognition ocr models, and want to train one of them for my native language. Right now i don't really understand how to do it, so i ask you: Can you please describe steps of what i should do.
I want to use models SAR or ABINet.

Thank you in advance and good luck.

**Comment by VietHoang1512** [comment]
He doesnt know anything, trust me. This is his copy-cat project and I'm pretty sure that he doesnt understand how things work under the hood @Globolik

**Comment by VietHoang1512** [comment]
Also for your information, my friend https://www.facebook.com/titmuoifrommrgardenfc is an expert in this field, you can contact him for further detailed guidance.
Sincerely.

**Comment by duclong1009** [comment]
This project was coded by Khanh. He is also an expert in this field. You can contact him https://www.facebook.com/profile.php?id=100009266195537. Good luck.

**Comment by tienlonghungson** [comment]
@Globolik sorry for the annoying of my friend @VietHoang1512 . Actually, the ones who are the masters in this field and also responsible for this project are  my other friends @dnkhanh45  and @phuc180155

**Comment by VietHoang1512** [comment]
![image](https://user-images.githubusercontent.com/52401767/150285711-333c3222-bf6e-46de-b73b-c78150769608.png)

**Comment by duclong1009** [comment]
@dnkhanh45  @phuc180155

**Comment by Globolik** [comment]
lol, @tienlonghungson thx for replying, but rn i've got to try (https://github.com/open-mmlab/mmocr/issues/741)

**Comment by VietHoang1512** [comment]
đbrr @duclong1009
